// <auto-generated />
namespace CinemaBookingSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _2_ReInitialDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2_ReInitialDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202212091526254_2_ReInitialDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
